require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'Steepfile'

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  AllowedPatterns: ['(\A|\s)#']
  Max: 128

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
  Max: 32

Metrics/BlockNesting:
  Max: 5

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'

Naming/MethodParameterName:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'ext/**/*'
